### ISSUE TITLE
Test 2 code not working

### ISSUE THREAD

**Issue by jdmillwood** [clbutler/RM_TRIPS#1]
The following code gives the error

> Error in rename(test2, lowextremety = qry_start) : 
  object 'qry_start' not found

It seems this is because the extremety headings are removed using select, and there are also still headings named "qry_start", etc. I am curious if the rename should be the other way around or if there is something else going on here. I am a little confused as to what this precise bit of code does, and was wondering if it could just be removed? Thanks for any help.

`#####test2#####
#next snippet of code keeps merged elements that should have been merged seperate

test2 <- test2 %>% dplyr::select(-c('lowextremety', 'highextremety', 'mergedfraglength'))

test2 <- rename(test2, lowextremety = qry_start)
test2 <- rename(test2, highextremety = qry_end)
test2 <- rename(test2, mergedfraglength = qry_width)`

**Comment by clbutler** [comment]
Hi @jdmillwood thanks for getting in touch! This bit of code is necessary (though admittedly a little clunky) 

essentially test 2 contains all TEs that likely don't want to be merged because the merged element would be longer than their RepBase entry (and thus likely represent separate insertion events).

so instead of using the new  merged 'extremity' coordinates we revert back to the original qry_start and qry_end coordinates (where no merging occured) - and then we rename them to match the column headers of test 1 so we can rbind later on

as to your issue, i'm unsure as to why  it is not working - test 2 should have qry_start and qry_end in it after you perform - 

#test2 <- test2 %>% dplyr::select(-c('lowextremety', 'highextremety', 'mergedfraglength'))

which are then simply renamed

Hopefully this clears it up a bit

**Comment by jdmillwood** [comment]
Hi @clbutler, thanks for the clarification. I am not that great with R, but I am thinking my error may be due to the fact that there are already columns labeled "qey_start", etc. after running 

#test2 <- test2 %>% dplyr::select(-c('lowextremety', 'highextremety', 'mergedfraglength'))

so when 

test2 <- rename(test2, lowextremety = qry_start)

is run, it can't create a second column labeled "qry_start". Also, when I run 

test2 <- test2 %>% dplyr::select(-c('lowextremety', 'highextremety', 'mergedfraglength')

it removes those three "extremety" columns, so I am confused as to how they are to be renamed anyway.

I am really sorry if I am missing something obvious here. Thanks for all your help.

**Comment by jdmillwood** [comment]
@clbutler is the rename command just mixed up? Should we be renaming the "qry_start" column "lowextremety", so it matches the name used for the merged fragments in test1?

**Comment by clbutler** [comment]
Hi @jdmillwood 

Firstly, no need to apologise! I think you're confused as to how the dplyr function rename works - the rename function in R works by following this rule 

rename(df, 'new_column_name' = 'old_column_name'

therefore our code which says "test2 <- rename(test2, lowextremety = qry_start)" should be renaming the column in our dataframe 'qry_start' to 'low extremety' - not the other way round

**Comment by clbutler** [comment]
> @clbutler is the rename command just mixed up? Should we be renaming the "qry_start" column "lowextremety", so it matches the name used for the merged fragments in test1?

yes you are right! this is what we want to achieve - confused why the code isn't working for you.

**Comment by clbutler** [comment]
can you try altering your code to say dplyr::rename rather than simply rename - I wonder if maybe another rename command is being used by your R :)

**Comment by jdmillwood** [comment]
I was in the process of doing that while you recommended it. This would be a great place for the "facepalm" emoji. That was exactly what the problem was. Apparently, the rename command was being used by the vector S4 program. On another note, you can use that rename command as well, you just have to change the layout of the command and add some quotes... I am so sorry for the blunder, and thank you so much for all the help. It is working just fine now, and my PhD research can continue! Thanks again!

**Comment by clbutler** [comment]
No problem - always good to be able to help. Best of luck in your PhD (im hoping to submit mine by end of month!). Feel free to contact me again if you need any help with this pipeline
